server:
  port: 8888
  servlet:
    context-path: /secondarymarket
    session:
      timeout: PT1H
  compression:
    enabled: true                           #\u5f00\u542fgzip\u538b\u7f29
  tomcat:
    max-http-post-size: -1                  #\u53d6\u6d88post\u5927\u5c0f\u9650\u5236
logging:
  level:
    com.zq.prd.sptl: debug
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  task:
    pool:
      core-pool-size: 10
      max-pool-size: 20
      queue-capacity: 1000
      keep-alive-seconds: 300
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/storedb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: 990610
    pool:
      initial-size: 2
      min-idle: 2
      max-active: 512
      max-wait: 50000
except-filter-url: login
